[package]
name = "ameba_blog_downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "*", features = ["full"] }
reqwest = { version = "*", features = ["default"] }
regex = { version = "*", features = ["default"] }
futures = { version = "*", features = ["default"] }
serde_json = { version = "*", features = ["default", "preserve_order"] }
ort = { git = "https://github.com/pykeio/ort", branch = "main", features = ["default"] }
# tract-onnx = { version = "*", features = ["default"] }
image = { version = "*", features = ["default", "jpeg", "png"] }
tracing-subscriber = { version = "*", features = ["fmt", "env-filter"] }
rand = { version = "*", features = ["default"] }
ndarray = { version = "*", features = ["default"] }